# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reviewEx01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reviewEx01
  pod 'SideMenu', '~> 6.0'
  pod 'youtube-ios-player-helper', '~> 0.1.4'
  
end
